"""add assignment association table

Revision ID: c26c6d9cf1ae
Revises: 099c118932b2
Create Date: 2024-10-05 19:59:43.039842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c26c6d9cf1ae'
down_revision = '099c118932b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'end_date')
    # ### end Alembic commands ###
